---
title: "Introduction to ggjoy"
author: "Claus O. Wilke"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 5
vignette: >
  %\VignetteIndexEntry{Introduction to ggjoy}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

Basic usage:
```{r}
library(ggplot2)
library(ggjoy)

ggplot(iris, aes(x=Sepal.Length, y=Species, group=Species)) + geom_joy()
```


## Gallery of examples

Temperatures in Lincoln, Nebraska. Modified from a [blog post](http://austinwehrwein.com/data-visualization/it-brings-me-ggjoy/) by Austin Wehrwein.
```{r message=FALSE, fig.width = 7.5, fig.height = 5}
ggplot(lincoln_weather, aes(x = `Mean Temperature [F]`, y = `Month`)) +
  geom_joy(scale = 3, rel_min_height = 0.01) +
  scale_x_continuous(expand = c(0.01, 0)) +
  scale_y_discrete(expand = c(0.01, 0)) +
  labs(title = 'Temperatures in Lincoln NE',
       subtitle = 'Mean temperatures (Fahrenheit) by month for 2016\nData: Original CSV from the Weather Underground') +
  theme_joy(font_size = 13, grid = T) + theme(axis.title.y = element_blank())
```

Evolution of movie lengths over time. Data from the IMDB, as provided in the ggplot2movies package.
```{r message=TRUE, fig.width = 5, fig.height = 6}
library(ggplot2movies)
ggplot(movies[movies$year>1912,], aes(x=length, y=year, group=year)) +
  geom_joy(scale=10, size=0.25, rel_min_height=0.03) +
  theme_joy() +
  scale_x_continuous(limits=c(1, 200), expand=c(0.01, 0)) +
  scale_y_reverse(breaks=c(2000, 1980, 1960, 1940, 1920, 1900), expand=c(0.01, 0))
```
